# Generated by Django 4.2 on 2023-04-29 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("updated_at", models.DateField(auto_created=True)),
                ("created_at", models.DateField(auto_created=True)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("49a75d19-1575-4dc2-b50e-c2870b1e1d8e"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Todo_Title", models.CharField(max_length=100)),
                ("Todo_Description", models.TextField()),
                ("is_Done", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
