# Generated by Django 4.2 on 2023-04-29 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("1f8178f4-4f91-4dcb-b9b7-364c40fefd24"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
