# Generated by Django 4.2 on 2023-04-30 05:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0002_alter_todo_created_at_alter_todo_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("f0426147-546e-4f78-aecc-e24e436c8ad0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="TodoTiming",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("f0426147-546e-4f78-aecc-e24e436c8ad0"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("timing", models.DateField()),
                (
                    "todo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="restapp.todo"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
