# Generated by Django 4.2 on 2023-04-30 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0005_alter_todo_uid_alter_todotiming_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("0115139f-5ebf-4f8d-a089-91fba4860034"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="todotiming",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("0115139f-5ebf-4f8d-a089-91fba4860034"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
