# Generated by Django 4.2 on 2023-04-30 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0007_todo_user_alter_todo_uid_alter_todotiming_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("e6ffce16-6e8d-462a-81fb-cb6e7d5f50ea"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="todotiming",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("e6ffce16-6e8d-462a-81fb-cb6e7d5f50ea"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
